language: php
dist: trusty
sudo: false

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  include:
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: hhvm
    - php: nightly
  allow_failures:
    - php: hhvm
    - php: nightly
  fast_finish: true

before_install:
  - composer self-update

install: composer update --prefer-dist --no-interaction

script: vendor/bin/phpunit --verbose
